import { RuleV1 as TrackingPlanRule } from '@segment/public-api-sdk-typescript';
import prettier from 'prettier';
import toCamelCase from 'lodash/camelCase';

const OUTPUT_FILE_HEADER = `/**
 * !!! Do not edit this file directly !!!
 * This file was generated by @blueshift-ui/analytics
 * To edit these event names, update the tracking plan in Segment and run the generate-event-types command again.
 *
 * @see https://varsity.atlassian.net/wiki/spaces/ENG/pages/1233879147/Generating+Event+Types
 */

/* eslint-disable */

`;

/**
 * Convert tracking plan rules to event names constant
 * @param trackingPlanRules - The rules from the tracking plan
 * @returns A string containing the event names from the tracking plan rules
 */
function trackingPlanRulesToEventNames(trackingPlanRules: TrackingPlanRule[]) {
  const trackingPlanTrackRules = trackingPlanRules.filter(
    (rule) => rule.type === TrackingPlanRule.TypeEnum.TRACK
  );

  const eventEntries = trackingPlanTrackRules
    .map((rule) => {
      if (!rule.key) {
        throw new Error(`Missing tracking plan rule key`);
      }

      return `${toCamelCase(rule.key)}: '${rule.key}',`;
    })
    .sort();

  const lines = [
    'const ANALYTICS_EVENT_NAMES = {',
    ...eventEntries,
    '};',
    '',
    'export default ANALYTICS_EVENT_NAMES;',
  ];

  return prettier.format(`${OUTPUT_FILE_HEADER}${lines.join('\n')}`, {
    parser: 'typescript',
    printWidth: 100,
    singleQuote: true,
    trailingComma: 'es5',
  });
}

export default trackingPlanRulesToEventNames;
