import { baseTokens as tokens } from '@blueshift-ui/tokens';

const customVariants = {
  bodyLarge: {
    fontSize: tokens.sys.typescale.sm.body.large.default.size,
    fontWeight: tokens.sys.typescale.sm.body.large.default.weight,
    letterSpacing: tokens.sys.typescale.sm.body.large.default.tracking,
    lineHeight: tokens.sys.typescale.sm.body.large.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.body.large.default.size,
      fontWeight: tokens.sys.typescale.lg.body.large.default.weight,
      letterSpacing: tokens.sys.typescale.lg.body.large.default.tracking,
      lineHeight: tokens.sys.typescale.lg.body.large.default.lineHeight,
    },
  },
  bodyLargeProminent: {
    fontSize: tokens.sys.typescale.sm.body.large.prominent.size,
    fontWeight: tokens.sys.typescale.sm.body.large.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.body.large.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.body.large.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.body.large.prominent.size,
      fontWeight: tokens.sys.typescale.lg.body.large.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.body.large.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.body.large.prominent.lineHeight,
    },
  },
  bodyMedium: {
    fontSize: tokens.sys.typescale.sm.body.medium.default.size,
    fontWeight: tokens.sys.typescale.sm.body.medium.default.weight,
    letterSpacing: tokens.sys.typescale.sm.body.medium.default.tracking,
    lineHeight: tokens.sys.typescale.sm.body.medium.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.body.medium.default.size,
      fontWeight: tokens.sys.typescale.lg.body.medium.default.weight,
      letterSpacing: tokens.sys.typescale.lg.body.medium.default.tracking,
      lineHeight: tokens.sys.typescale.lg.body.medium.default.lineHeight,
    },
  },
  bodyMediumProminent: {
    fontSize: tokens.sys.typescale.sm.body.medium.prominent.size,
    fontWeight: tokens.sys.typescale.sm.body.medium.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.body.medium.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.body.medium.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.body.medium.prominent.size,
      fontWeight: tokens.sys.typescale.lg.body.medium.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.body.medium.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.body.medium.prominent.lineHeight,
    },
  },
  bodySmall: {
    fontSize: tokens.sys.typescale.sm.body.small.default.size,
    fontWeight: tokens.sys.typescale.sm.body.small.default.weight,
    letterSpacing: tokens.sys.typescale.sm.body.small.default.tracking,
    lineHeight: tokens.sys.typescale.sm.body.small.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.body.small.default.size,
      fontWeight: tokens.sys.typescale.lg.body.small.default.weight,
      letterSpacing: tokens.sys.typescale.lg.body.small.default.tracking,
      lineHeight: tokens.sys.typescale.lg.body.small.default.lineHeight,
    },
  },
  displayLarge: {
    fontSize: tokens.sys.typescale.sm.display.large.size,
    fontWeight: tokens.sys.typescale.sm.display.large.weight,
    letterSpacing: tokens.sys.typescale.sm.display.large.tracking,
    lineHeight: tokens.sys.typescale.sm.display.large.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.display.large.size,
      fontWeight: tokens.sys.typescale.lg.display.large.weight,
      letterSpacing: tokens.sys.typescale.lg.display.large.tracking,
      lineHeight: tokens.sys.typescale.lg.display.large.lineHeight,
    },
  },
  displayMedium: {
    fontSize: tokens.sys.typescale.sm.display.medium.size,
    fontWeight: tokens.sys.typescale.sm.display.medium.weight,
    letterSpacing: tokens.sys.typescale.sm.display.medium.tracking,
    lineHeight: tokens.sys.typescale.sm.display.medium.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.display.medium.size,
      fontWeight: tokens.sys.typescale.lg.display.medium.weight,
      letterSpacing: tokens.sys.typescale.lg.display.medium.tracking,
      lineHeight: tokens.sys.typescale.lg.display.medium.lineHeight,
    },
  },
  displaySmall: {
    fontSize: tokens.sys.typescale.sm.display.small.size,
    fontWeight: tokens.sys.typescale.sm.display.small.weight,
    letterSpacing: tokens.sys.typescale.sm.display.small.tracking,
    lineHeight: tokens.sys.typescale.sm.display.small.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.display.small.size,
      fontWeight: tokens.sys.typescale.lg.display.small.weight,
      letterSpacing: tokens.sys.typescale.lg.display.small.tracking,
      lineHeight: tokens.sys.typescale.lg.display.small.lineHeight,
    },
  },
  headlineLarge: {
    fontSize: tokens.sys.typescale.sm.headline.large.size,
    fontWeight: tokens.sys.typescale.sm.headline.large.weight,
    letterSpacing: tokens.sys.typescale.sm.headline.large.tracking,
    lineHeight: tokens.sys.typescale.sm.headline.large.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.headline.large.size,
      fontWeight: tokens.sys.typescale.lg.headline.large.weight,
      letterSpacing: tokens.sys.typescale.lg.headline.large.tracking,
      lineHeight: tokens.sys.typescale.lg.headline.large.lineHeight,
    },
  },
  headlineMedium: {
    fontSize: tokens.sys.typescale.sm.headline.medium.size,
    fontWeight: tokens.sys.typescale.sm.headline.medium.weight,
    letterSpacing: tokens.sys.typescale.sm.headline.medium.tracking,
    lineHeight: tokens.sys.typescale.sm.headline.medium.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.headline.medium.size,
      fontWeight: tokens.sys.typescale.lg.headline.medium.weight,
      letterSpacing: tokens.sys.typescale.lg.headline.medium.tracking,
      lineHeight: tokens.sys.typescale.lg.headline.medium.lineHeight,
    },
  },
  headlineSmall: {
    fontSize: tokens.sys.typescale.sm.headline.small.size,
    fontWeight: tokens.sys.typescale.sm.headline.small.weight,
    letterSpacing: tokens.sys.typescale.sm.headline.small.tracking,
    lineHeight: tokens.sys.typescale.sm.headline.small.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.headline.small.size,
      fontWeight: tokens.sys.typescale.lg.headline.small.weight,
      letterSpacing: tokens.sys.typescale.lg.headline.small.tracking,
      lineHeight: tokens.sys.typescale.lg.headline.small.lineHeight,
    },
  },
  labelLarge: {
    fontSize: tokens.sys.typescale.sm.label.large.default.size,
    fontWeight: tokens.sys.typescale.sm.label.large.default.weight,
    letterSpacing: tokens.sys.typescale.sm.label.large.default.tracking,
    lineHeight: tokens.sys.typescale.sm.label.large.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.label.large.default.size,
      fontWeight: tokens.sys.typescale.lg.label.large.default.weight,
      letterSpacing: tokens.sys.typescale.lg.label.large.default.tracking,
      lineHeight: tokens.sys.typescale.lg.label.large.default.lineHeight,
    },
  },
  labelLargeProminent: {
    fontSize: tokens.sys.typescale.sm.label.large.prominent.size,
    fontWeight: tokens.sys.typescale.sm.label.large.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.label.large.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.label.large.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.label.large.prominent.size,
      fontWeight: tokens.sys.typescale.lg.label.large.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.label.large.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.label.large.prominent.lineHeight,
    },
  },
  labelMedium: {
    fontSize: tokens.sys.typescale.sm.label.medium.default.size,
    fontWeight: tokens.sys.typescale.sm.label.medium.default.weight,
    letterSpacing: tokens.sys.typescale.sm.label.medium.default.tracking,
    lineHeight: tokens.sys.typescale.sm.label.medium.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.label.medium.default.size,
      fontWeight: tokens.sys.typescale.lg.label.medium.default.weight,
      letterSpacing: tokens.sys.typescale.lg.label.medium.default.tracking,
      lineHeight: tokens.sys.typescale.lg.label.medium.default.lineHeight,
    },
  },
  labelMediumProminent: {
    fontSize: tokens.sys.typescale.sm.label.medium.prominent.size,
    fontWeight: tokens.sys.typescale.sm.label.medium.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.label.medium.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.label.medium.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.label.medium.prominent.size,
      fontWeight: tokens.sys.typescale.lg.label.medium.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.label.medium.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.label.medium.prominent.lineHeight,
    },
  },
  labelSmall: {
    fontSize: tokens.sys.typescale.sm.label.small.default.size,
    fontWeight: tokens.sys.typescale.sm.label.small.default.weight,
    letterSpacing: tokens.sys.typescale.sm.label.small.default.tracking,
    lineHeight: tokens.sys.typescale.sm.label.small.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.label.small.default.size,
      fontWeight: tokens.sys.typescale.lg.label.small.default.weight,
      letterSpacing: tokens.sys.typescale.lg.label.small.default.tracking,
      lineHeight: tokens.sys.typescale.lg.label.small.default.lineHeight,
    },
  },
  labelSmallProminent: {
    fontSize: tokens.sys.typescale.sm.label.small.prominent.size,
    fontWeight: tokens.sys.typescale.sm.label.small.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.label.small.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.label.small.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.label.small.prominent.size,
      fontWeight: tokens.sys.typescale.lg.label.small.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.label.small.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.label.small.prominent.lineHeight,
    },
  },
  titleLarge: {
    fontSize: tokens.sys.typescale.sm.title.large.default.size,
    fontWeight: tokens.sys.typescale.sm.title.large.default.weight,
    letterSpacing: tokens.sys.typescale.sm.title.large.default.tracking,
    lineHeight: tokens.sys.typescale.sm.title.large.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.title.large.default.size,
      fontWeight: tokens.sys.typescale.lg.title.large.default.weight,
      letterSpacing: tokens.sys.typescale.lg.title.large.default.tracking,
      lineHeight: tokens.sys.typescale.lg.title.large.default.lineHeight,
    },
  },
  titleLargeProminent: {
    fontSize: tokens.sys.typescale.sm.title.large.prominent.size,
    fontWeight: tokens.sys.typescale.sm.title.large.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.title.large.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.title.large.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.title.large.prominent.size,
      fontWeight: tokens.sys.typescale.lg.title.large.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.title.large.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.title.large.prominent.lineHeight,
    },
  },
  titleMedium: {
    fontSize: tokens.sys.typescale.sm.title.medium.default.size,
    fontWeight: tokens.sys.typescale.sm.title.medium.default.weight,
    letterSpacing: tokens.sys.typescale.sm.title.medium.default.tracking,
    lineHeight: tokens.sys.typescale.sm.title.medium.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.title.medium.default.size,
      fontWeight: tokens.sys.typescale.lg.title.medium.default.weight,
      letterSpacing: tokens.sys.typescale.lg.title.medium.default.tracking,
      lineHeight: tokens.sys.typescale.lg.title.medium.default.lineHeight,
    },
  },
  titleMediumProminent: {
    fontSize: tokens.sys.typescale.sm.title.medium.prominent.size,
    fontWeight: tokens.sys.typescale.sm.title.medium.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.title.medium.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.title.medium.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.title.medium.prominent.size,
      fontWeight: tokens.sys.typescale.lg.title.medium.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.title.medium.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.title.medium.prominent.lineHeight,
    },
  },
  titleSmall: {
    fontSize: tokens.sys.typescale.sm.title.small.default.size,
    fontWeight: tokens.sys.typescale.sm.title.small.default.weight,
    letterSpacing: tokens.sys.typescale.sm.title.small.default.tracking,
    lineHeight: tokens.sys.typescale.sm.title.small.default.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.title.small.default.size,
      fontWeight: tokens.sys.typescale.lg.title.small.default.weight,
      letterSpacing: tokens.sys.typescale.lg.title.small.default.tracking,
      lineHeight: tokens.sys.typescale.lg.title.small.default.lineHeight,
    },
  },
  titleSmallProminent: {
    fontSize: tokens.sys.typescale.sm.title.small.prominent.size,
    fontWeight: tokens.sys.typescale.sm.title.small.prominent.weight,
    letterSpacing: tokens.sys.typescale.sm.title.small.prominent.tracking,
    lineHeight: tokens.sys.typescale.sm.title.small.prominent.lineHeight,
    [`@media (min-width:${tokens.sys.breakpoint.md}px)`]: {
      fontSize: tokens.sys.typescale.lg.title.small.prominent.size,
      fontWeight: tokens.sys.typescale.lg.title.small.prominent.weight,
      letterSpacing: tokens.sys.typescale.lg.title.small.prominent.tracking,
      lineHeight: tokens.sys.typescale.lg.title.small.prominent.lineHeight,
    },
  },
};

const defaultVariants = {
  h1: customVariants.displayLarge,
  h2: customVariants.displayMedium,
  h3: customVariants.displaySmall,
  h4: customVariants.headlineLarge,
  h5: customVariants.headlineMedium,
  h6: customVariants.headlineSmall,
  body1: customVariants.bodyLarge,
  body2: customVariants.bodyMedium,
  button: customVariants.labelLarge,
  caption: customVariants.labelLarge,
  overline: customVariants.labelMedium,
  subtitle1: customVariants.titleLarge,
  subtitle2: customVariants.titleMedium,
};

const typography = {
  fontFamily: [tokens.ref.typeface.brand, tokens.ref.typeface.plain].join(','),
  ...customVariants,
  ...defaultVariants,
};

export default typography;
